# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemode', '0002_auto_20170920_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoredurl',
            name='description',
            field=models.CharField(help_text='What this URL pattern covers.', max_length=75),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='is_being_performed',
            field=models.BooleanField(default=False, verbose_name='In Maintenance Mode'),
        ),
    ]
